SELECT TOP 1000
    'Ganze Hierarchie' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER"
ORDER BY HIERARCHY_LEVEL;
 	

SELECT TOP 1000
    'Filter auf ein Knoten' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"START_RANK",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_IP"
	(placeholder."$$IP_NODE_ID$$"=>'Central and South America');
	
SELECT TOP 1000
    'DESCENDANTS von Europa' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_DESCENDANTS"
	(placeholder."$$IP_1$$"=>'Europe');	
	
SELECT TOP 1000
    'DESCENDANTS von N.Amerika' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_DESCENDANTS"
	(placeholder."$$IP_1$$"=>'North America');	
	
SELECT TOP 1000
    'DESCENDANTS von Mit.und Zent.Amerika' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_DESCENDANTS"
	(placeholder."$$IP_1$$"=>'Central and South America');
	
SELECT TOP 1000
    'DESCENDANTS von Ozeanien' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_DESCENDANTS"
	(placeholder."$$IP_1$$"=>'Oceany');	


SELECT TOP 1000
    'Ancestors von United Kingdom' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"START_RANK",
	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_ANCESTORS"
	(placeholder."$$IP_1$$"=>'United Kingdom');
	
SELECT TOP 1000
    'Ancestors von Australien' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"START_RANK",
	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_ANCESTORS"
	(placeholder."$$IP_1$$"=>'Australia');	
	
	
SELECT TOP 1000
    'Gebr. von United Kingdom' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"START_RANK",
	"HIERARCHY_SIBLING_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_SIBLINGS"
	(placeholder."$$IP_1$$"=>'United Kingdom');
	
SELECT TOP 1000
    'Gebr. von USA' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"START_RANK",
	"HIERARCHY_SIBLING_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_SIBLINGS"
	(placeholder."$$IP_1$$"=>'United States');
	
SELECT TOP 1000
    'Gebr. von United Mexico' AS DESCR,
	"PARENT_ID",
	"NODE_ID",
	"START_RANK",
	"HIERARCHY_SIBLING_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"
FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_SIBLINGS"
	(placeholder."$$IP_1$$"=>'Mexico');	
	
SELECT TOP 1000
    '.. and all above ' AS DESCR,
	"START_RANK",
    "START_ID",
	"NODE_ID",    
	"PARENT_ID",

	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"

FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_ANCESTORS_WITH_DIST"
	(placeholder."$$IP_1$$"=>'United Kingdom', 
	placeholder."$$IP_DIST_FROM$$"=>-10, 
	placeholder."$$IP_DIST_TO$$"=>0);	
	
SELECT TOP 1000
    '.. all above only ' AS DESCR,
	"START_RANK",
    "START_ID",
	"NODE_ID",    
	"PARENT_ID",

	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"

FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_ANCESTORS_WITH_DIST"
	(placeholder."$$IP_1$$"=>'United Kingdom', 
	placeholder."$$IP_DIST_FROM$$"=>-10, 
	placeholder."$$IP_DIST_TO$$"=>-1);	
	

	
SELECT TOP 1000
    'Parent of .. ' AS DESCR,
	"START_RANK",
    "START_ID",
	"NODE_ID",    
	"PARENT_ID",

	"HIERARCHY_DISTANCE",
	"HIERARCHY_RANK",
	"HIERARCHY_TREE_SIZE",
	"HIERARCHY_PARENT_RANK",
	"HIERARCHY_LEVEL",
	"HIERARCHY_IS_CYCLE",
	"HIERARCHY_IS_ORPHAN"

FROM "ANALYTICS_HDI_DB_1"."COUNTRY_HIER_NAV_ANCESTORS_WITH_DIST"
	(placeholder."$$IP_1$$"=>'United Kingdom', 
	placeholder."$$IP_DIST_FROM$$"=>-1, 
	placeholder."$$IP_DIST_TO$$"=>-1);	